//src\app\layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat,EB_Garamond } from "next/font/google";
import "./globals.css";
import GlassNavbar from "@/components/GlassNavbar";
import { RevealProvider } from "./context/RevealContext";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
const timesNewRoman = EB_Garamond({
  variable: "--font-timesnewroman", // This matches your inline style!
  subsets: ["latin"],
  weight: ["400"], // EB Garamond doesn't usually use 300, 400 is very elegant
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${timesNewRoman.variable} ${geistSans.variable} ${geistMono.variable} ${montserrat.variable} min-h-screen antialiased`}
    >
      <body className="min-h-screen flex flex-col">
  <SmoothScrollProvider>
    <RevealProvider>
      {children}
    </RevealProvider>
  </SmoothScrollProvider>
</body>
    </html>
  );
}